general:
    min_wait: 100
    max_wait: 100
    workspace_root:  /hxdepots/work

# Perforce benchmark testing parameters
# Specify password if required
perforce:
    port:       
    - ssl:10.0.0.181:1666
    # - replica1:1666
    user:       bruno
    charset:
    password:   "F@stSCM!"
    options:  noallwrite noclobber nocompress unlocked nomodtime rmdir
    sync_progress_size_interval: 100 * 1000 * 1000
    # The following should not include trailing /...
    # Will be used as base for selection after running "p4 dirs %s/*"
    repoPath:   //depot/01
    repoSubDir: "*"
    repoSubDirNum: 5
    # How many times to repeat the loop
    repeat: 5
    # sync_args: any extra sync arguments. This will result in the spawning of a "p4" command
    # Example to avoid actually writing files to filesystem on client side:
    #sync_args: -vfilesys.client.nullsync=1
    # Any other -v or similar options possible.
    # Note that the following commands will be passed automatically: -p/-u/-c
