general:
    min_wait: 100
    max_wait: 100
    workspace_root:  /hxdepots/work

# Perforce benchmark testing parameters
# Specify password if required
perforce:
    # Array of ports - can include ssl prefix. Allows for random selection of edge servers
    port:       
    - ssl:10.0.0.181:1666
    user:       bruno
    charset:
    password:   "my!Password"
    options:  noallwrite noclobber nocompress unlocked nomodtime rmdir
    sync_progress_size_interval: 100 * 1000 * 1000
    # repoPath: should not include trailing /...
    #   If it includes "*" will be used as base for selection after running "p4 dirs" on it
    repoPath:   //depot/01
    # repoDirNum: (numeric) Number of entries to randomly select from the above "p4 dirs" output if relevant
    repoDirNum: 5
    # How many times to repeat the loop
    repeat: 5
    # sync_args: any extra sync arguments. This will result in the spawning of a "p4" command
    # Example to avoid actually writing files to filesystem on client side:
    #sync_args: -vfilesys.client.nullsync=1
    # Any other -v or similar options possible.
    # Note that the following commands will be passed automatically: -p/-u/-c
