- name: Tidy up after p4benchmark scripts
  hosts: bench_clients
  tasks:

  - name: Kill locust processes if they exist
    shell: pkill --full 'locust' || true
    ignore_errors: yes

  - name: Remove base directory which has client workspaces
    file:
      path: "{{workspace_common_dir}}"
      state: absent

