- name: Run p4benchmark stuff for replicas
  hosts: bench_servers
  tasks:

  - name: Copy relevant monitoring files
    copy:
      src: "{{item}}"
      dest: "{{bench_dir}}"
      mode: 0755
    with_fileglob:
    - "{{bench_dir}}/run_monitor.sh"

  - command:  "{{bench_dir}}/run_monitor.sh"
    args:
      chdir: "{{bench_dir}}"
    async: 10
    poll: 0

