- name: Remove p4benchmark logs on server machines
  hosts: bench_servers
  remote_user: '{{ remote_user }}'
  tasks:

    - name: Find files to delete
      find:
        paths: "/p4/{{sdp_instance}}/logs"
        patterns: "log"
      register: files_to_delete

    - name: Remove found files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"
